Import('env')


env.BuildPython(
    target  = ['#build/clean/candidato.csv',
    	       '#build/clean/politico.csv'],
    source  = ['#source/candidato_politico.py']
)

env.BuildPython(
    target  = ['#build/insert/candidato.txt',
    	       '#build/insert/politico.txt'],
    source  = ['#source/insert.py',
    	       '#source/define_db_schemas.py',
	       '#source/eleicao.csv',
	       '#build/clean/candidato.csv',
	       '#build/clean/politico.csv']
)
